/*Generated by WaveMaker Studio*/

package com.testdb_hsql.rolodex.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testdb_hsql.rolodex.*;


/**
 * ServiceImpl object for domain model class Actor.
 * @see com.testdb_hsql.rolodex.Actor
 */
@Service("rolodex.ActorService")
public class ActorServiceImpl implements ActorService {


    private static final Logger LOGGER = LoggerFactory.getLogger(ActorServiceImpl.class);

    @Autowired
    @Qualifier("rolodex.ActorDao")
    private WMGenericDao<Actor, Integer> wmGenericDao;
    public void setWMGenericDao(WMGenericDao<Actor, Integer> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "rolodexTransactionManager")
     public Page<Actor> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "rolodexTransactionManager")
    @Override
    public Actor create(Actor actor) {
        LOGGER.debug("Creating a new actor with information: {}" , actor);
        return this.wmGenericDao.create(actor);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "rolodexTransactionManager")
    @Override
    public Actor delete(Integer actorId) throws EntityNotFoundException {
        LOGGER.debug("Deleting actor with id: {}" , actorId);
        Actor deleted = this.wmGenericDao.findById(actorId);
        if (deleted == null) {
            LOGGER.debug("No actor found with id: {}" , actorId);
            throw new EntityNotFoundException(String.valueOf(actorId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public Page<Actor> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all actors");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public Page<Actor> findAll(Pageable pageable) {
        LOGGER.debug("Finding all actors");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public Actor findById(Integer id) throws EntityNotFoundException {
        LOGGER.debug("Finding actor by id: {}" , id);
        Actor actor=this.wmGenericDao.findById(id);
        if(actor==null){
            LOGGER.debug("No actor found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return actor;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "rolodexTransactionManager")
    @Override
    public Actor update(Actor updated) throws EntityNotFoundException {
        LOGGER.debug("Updating actor with information: {}" , updated);
        this.wmGenericDao.update(updated);
        return this.wmGenericDao.findById((Integer)updated.getActorId());
    }

    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


