/*Generated by WaveMaker Studio*/

package com.testdb_hsql.rolodex.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testdb_hsql.rolodex.*;


/**
 * ServiceImpl object for domain model class Address.
 * @see com.testdb_hsql.rolodex.Address
 */
@Service("rolodex.AddressService")
public class AddressServiceImpl implements AddressService {


    private static final Logger LOGGER = LoggerFactory.getLogger(AddressServiceImpl.class);

    @Autowired
    @Qualifier("rolodex.AddressDao")
    private WMGenericDao<Address, Integer> wmGenericDao;
    public void setWMGenericDao(WMGenericDao<Address, Integer> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "rolodexTransactionManager")
     public Page<Address> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "rolodexTransactionManager")
    @Override
    public Address create(Address address) {
        LOGGER.debug("Creating a new address with information: {}" , address);
        return this.wmGenericDao.create(address);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "rolodexTransactionManager")
    @Override
    public Address delete(Integer addressId) throws EntityNotFoundException {
        LOGGER.debug("Deleting address with id: {}" , addressId);
        Address deleted = this.wmGenericDao.findById(addressId);
        if (deleted == null) {
            LOGGER.debug("No address found with id: {}" , addressId);
            throw new EntityNotFoundException(String.valueOf(addressId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public Page<Address> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all addresss");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public Page<Address> findAll(Pageable pageable) {
        LOGGER.debug("Finding all addresss");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public Address findById(Integer id) throws EntityNotFoundException {
        LOGGER.debug("Finding address by id: {}" , id);
        Address address=this.wmGenericDao.findById(id);
        if(address==null){
            LOGGER.debug("No address found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return address;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "rolodexTransactionManager")
    @Override
    public Address update(Address updated) throws EntityNotFoundException {
        LOGGER.debug("Updating address with information: {}" , updated);
        this.wmGenericDao.update(updated);
        return this.wmGenericDao.findById((Integer)updated.getAddressId());
    }

    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


