/*Generated by WaveMaker Studio*/

package com.testdb_hsql.rolodex.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testdb_hsql.rolodex.*;


/**
 * ServiceImpl object for domain model class City.
 * @see com.testdb_hsql.rolodex.City
 */
@Service("rolodex.CityService")
public class CityServiceImpl implements CityService {


    private static final Logger LOGGER = LoggerFactory.getLogger(CityServiceImpl.class);

    @Autowired
    @Qualifier("rolodex.CityDao")
    private WMGenericDao<City, Integer> wmGenericDao;
    public void setWMGenericDao(WMGenericDao<City, Integer> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "rolodexTransactionManager")
     public Page<City> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "rolodexTransactionManager")
    @Override
    public City create(City city) {
        LOGGER.debug("Creating a new city with information: {}" , city);
        return this.wmGenericDao.create(city);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "rolodexTransactionManager")
    @Override
    public City delete(Integer cityId) throws EntityNotFoundException {
        LOGGER.debug("Deleting city with id: {}" , cityId);
        City deleted = this.wmGenericDao.findById(cityId);
        if (deleted == null) {
            LOGGER.debug("No city found with id: {}" , cityId);
            throw new EntityNotFoundException(String.valueOf(cityId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public Page<City> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all citys");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public Page<City> findAll(Pageable pageable) {
        LOGGER.debug("Finding all citys");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public City findById(Integer id) throws EntityNotFoundException {
        LOGGER.debug("Finding city by id: {}" , id);
        City city=this.wmGenericDao.findById(id);
        if(city==null){
            LOGGER.debug("No city found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return city;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "rolodexTransactionManager")
    @Override
    public City update(City updated) throws EntityNotFoundException {
        LOGGER.debug("Updating city with information: {}" , updated);
        this.wmGenericDao.update(updated);
        return this.wmGenericDao.findById((Integer)updated.getCityId());
    }

    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


