/*Generated by WaveMaker Studio*/

package com.testdb_hsql.rolodex.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testdb_hsql.rolodex.*;


/**
 * ServiceImpl object for domain model class Country.
 * @see com.testdb_hsql.rolodex.Country
 */
@Service("rolodex.CountryService")
public class CountryServiceImpl implements CountryService {


    private static final Logger LOGGER = LoggerFactory.getLogger(CountryServiceImpl.class);

    @Autowired
    @Qualifier("rolodex.CountryDao")
    private WMGenericDao<Country, Integer> wmGenericDao;
    public void setWMGenericDao(WMGenericDao<Country, Integer> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "rolodexTransactionManager")
     public Page<Country> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "rolodexTransactionManager")
    @Override
    public Country create(Country country) {
        LOGGER.debug("Creating a new country with information: {}" , country);
        return this.wmGenericDao.create(country);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "rolodexTransactionManager")
    @Override
    public Country delete(Integer countryId) throws EntityNotFoundException {
        LOGGER.debug("Deleting country with id: {}" , countryId);
        Country deleted = this.wmGenericDao.findById(countryId);
        if (deleted == null) {
            LOGGER.debug("No country found with id: {}" , countryId);
            throw new EntityNotFoundException(String.valueOf(countryId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public Page<Country> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all countrys");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public Page<Country> findAll(Pageable pageable) {
        LOGGER.debug("Finding all countrys");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public Country findById(Integer id) throws EntityNotFoundException {
        LOGGER.debug("Finding country by id: {}" , id);
        Country country=this.wmGenericDao.findById(id);
        if(country==null){
            LOGGER.debug("No country found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return country;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "rolodexTransactionManager")
    @Override
    public Country update(Country updated) throws EntityNotFoundException {
        LOGGER.debug("Updating country with information: {}" , updated);
        this.wmGenericDao.update(updated);
        return this.wmGenericDao.findById((Integer)updated.getCountryId());
    }

    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


