/*Generated by WaveMaker Studio*/

package com.testdb_hsql.rolodex.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testdb_hsql.rolodex.*;


/**
 * ServiceImpl object for domain model class Film.
 * @see com.testdb_hsql.rolodex.Film
 */
@Service("rolodex.FilmService")
public class FilmServiceImpl implements FilmService {


    private static final Logger LOGGER = LoggerFactory.getLogger(FilmServiceImpl.class);

    @Autowired
    @Qualifier("rolodex.FilmDao")
    private WMGenericDao<Film, Integer> wmGenericDao;
    public void setWMGenericDao(WMGenericDao<Film, Integer> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "rolodexTransactionManager")
     public Page<Film> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "rolodexTransactionManager")
    @Override
    public Film create(Film film) {
        LOGGER.debug("Creating a new film with information: {}" , film);
        return this.wmGenericDao.create(film);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "rolodexTransactionManager")
    @Override
    public Film delete(Integer filmId) throws EntityNotFoundException {
        LOGGER.debug("Deleting film with id: {}" , filmId);
        Film deleted = this.wmGenericDao.findById(filmId);
        if (deleted == null) {
            LOGGER.debug("No film found with id: {}" , filmId);
            throw new EntityNotFoundException(String.valueOf(filmId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public Page<Film> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all films");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public Page<Film> findAll(Pageable pageable) {
        LOGGER.debug("Finding all films");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public Film findById(Integer id) throws EntityNotFoundException {
        LOGGER.debug("Finding film by id: {}" , id);
        Film film=this.wmGenericDao.findById(id);
        if(film==null){
            LOGGER.debug("No film found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return film;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "rolodexTransactionManager")
    @Override
    public Film update(Film updated) throws EntityNotFoundException {
        LOGGER.debug("Updating film with information: {}" , updated);
        this.wmGenericDao.update(updated);
        return this.wmGenericDao.findById((Integer)updated.getFilmId());
    }

    @Transactional(readOnly = true, value = "rolodexTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


