/*Generated by WaveMaker Studio*/

package com.testdb_hsql.rolodex.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testdb_hsql.rolodex.*;

/**
 * Service object for domain model class Inventory.
 * @see com.testdb_hsql.rolodex.Inventory
 */

public interface InventoryService {
   /**
	 * Creates a new inventory.
	 * 
	 * @param created
	 *            The information of the created inventory.
	 * @return The created inventory.
	 */
	public Inventory create(Inventory created);

	/**
	 * Deletes a inventory.
	 * 
	 * @param inventoryId
	 *            The id of the deleted inventory.
	 * @return The deleted inventory.
	 * @throws EntityNotFoundException
	 *             if no inventory is found with the given id.
	 */
	public Inventory delete(Integer inventoryId) throws EntityNotFoundException;

	/**
	 * Finds all inventorys.
	 * 
	 * @return A list of inventorys.
	 */
	public Page<Inventory> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<Inventory> findAll(Pageable pageable);
	
	/**
	 * Finds inventory by id.
	 * 
	 * @param id
	 *            The id of the wanted inventory.
	 * @return The found inventory. If no inventory is found, this method returns
	 *         null.
	 */
	public Inventory findById(Integer id) throws EntityNotFoundException;
	/**
	 * Updates the information of a inventory.
	 * 
	 * @param updated
	 *            The information of the updated inventory.
	 * @return The updated inventory.
	 * @throws EntityNotFoundException
	 *             if no inventory is found with given id.
	 */
	public Inventory update(Inventory updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the inventorys in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the inventory.
	 */

	public long countAll();


    public Page<Inventory> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

