/*Generated by WaveMaker Studio*/

package com.testdb_hsql.rolodex;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Embeddable;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * FilmActorId generated by hbm2java
 */
@Embeddable
public class FilmActorId  implements java.io.Serializable
 {


private Integer actorId;
private Integer filmId;

    public FilmActorId() {
    }




    

    @Column(name="ACTOR_ID", nullable=false)
    public Integer getActorId() {
        return this.actorId;
    }
    
    public void setActorId(Integer actorId) {
        this.actorId = actorId;
    }

    

    @Column(name="FILM_ID", nullable=false)
    public Integer getFilmId() {
        return this.filmId;
    }
    
    public void setFilmId(Integer filmId) {
        this.filmId = filmId;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof FilmActorId) )
		 return false;

		 FilmActorId that = ( FilmActorId ) o;

         return ( (this.getActorId()==that.getActorId()) || ( this.getActorId()!=null && that.getActorId()!=null && this.getActorId().equals(that.getActorId()) ) )
 && ( (this.getFilmId()==that.getFilmId()) || ( this.getFilmId()!=null && that.getFilmId()!=null && this.getFilmId().equals(that.getFilmId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getActorId() == null ? 0 : this.getActorId().hashCode() );
         result = 37 * result + ( getFilmId() == null ? 0 : this.getFilmId().hashCode() );

         return result;
     }


}

